package com.shanlin.framework.webservice.gzt;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
* <p>
* An example of how this class may be used:
* <pre>
* QueryValidatorServicesService service = new QueryValidatorServicesService();
* QueryValidatorServices portType = service.getQueryValidatorServices();
* portType.querySingle(...);
* </pre>
* </p>
 * 
 */
@WebServiceClient(name = "QueryValidatorServicesService", targetNamespace = "http://app.service.validator.businesses.gboss.id5.cn", wsdlLocation = "http://gboss.id5.cn/services/QueryValidatorServices?wsdl")
public class QueryValidatorServicesService extends Service
{
    
    private final static URL QUERYVALIDATORSERVICESSERVICE_WSDL_LOCATION;
    
    private final static Logger logger =
        LoggerFactory.getLogger(com.shanlin.framework.webservice.gzt.QueryValidatorServicesService.class.getName());
    
    static
    {
        URL url = null;
        try
        {
            URL baseUrl;
            baseUrl = com.shanlin.framework.webservice.gzt.QueryValidatorServicesService.class.getResource(".");
            url = new URL(baseUrl, "http://gboss.id5.cn/services/QueryValidatorServices?wsdl");
        }
        catch (MalformedURLException e)
        {
            logger.warn("Failed to create URL for the wsdl Location: 'http://gboss.id5.cn/services/QueryValidatorServices?wsdl', retrying as a local file");
            logger.warn(e.getMessage());
        }
        QUERYVALIDATORSERVICESSERVICE_WSDL_LOCATION = url;
    }
    
    public QueryValidatorServicesService(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }
    
    public QueryValidatorServicesService()
    {
        super(QUERYVALIDATORSERVICESSERVICE_WSDL_LOCATION, new QName(
            "http://app.service.validator.businesses.gboss.id5.cn", "QueryValidatorServicesService"));
    }
    
    /**
     * 
     * @return
     *     returns QueryValidatorServices
     */
    @WebEndpoint(name = "QueryValidatorServices")
    public QueryValidatorServices getQueryValidatorServices()
    {
        return super.getPort(new QName("http://app.service.validator.businesses.gboss.id5.cn", "QueryValidatorServices"),
            QueryValidatorServices.class);
    }
    
}
